const appConstants = {
  emptyLat: 'Please Enter Lattitude.',
  emptyLng: 'Please Enter Longitude.',
  latPlaceholder: '78.347837',
  lngPlaceholder: '72.83478',
  passGenerateErr: 'Unable to generate the Wallet Pass.',
  storeName: 'PopcornApps',
  browserSettingErr: 'Please switch on your browser location setting.',
  saveSessionErr: 'Unable to save session.',
  iphone: 'iphone',
  android: 'android',
  cookieName: 'data',
  sessionCookie: 'sessionId',
  storeId: 'storeId',
  wishlistData: 'wishlistData',
  journeyStage: 'journeyStage',
  journeyCompleted: 'journeyCompleted',
  notOnDisplay: 'notOnDisplay',
  busyDevices: 'busyDevices',
  timeoutSpan: 6000,
  latKey: 'lat',
  lngKey: 'lng',

};
export default appConstants;