const userLanguage = {
    'en' : {
        'youMadeIt': 'You made it!',
        'welcomeHeader' : 'Welcome to Contoso Redmond',
        'welcomeMsg' : 'Walk towards the Microsoft area and tap below when you arrive.',
        'iAmHere' : "I'M HERE!",
        'cancel' : 'CANCEL',
        'landingPageHeader' : 'Find the perfect PC.',
        'chooseSubHeader' : 'choose any option below to explore Windows 10 devices.',
        'panelHeader1' : 'Help Me Choose',
        'panelSubHeader1' : 'Find your perfect device in few easy steps.',
        'panelHeader2' : 'Windows & Office',
        'panelSubHeader2' : 'Explore based on the software and features you use most.',
        'panelSubHeader3' : 'Find devices with all the hardware features you need.',
        'panelHeader3' : 'Hardware',
        'panelHeader4' : 'Windows Premium Collection',
        'panelSubHeader4' : 'View all reommended devices.',
        'recommended' : 'Recommended Devices',
        'learnMore' : 'Learn more',
        'successMsgCaption1' : 'Tap to find your device and look for the ',
        'successMsgCaption2' : 'light',
        'blueLight' : 'blue',
        'tapFind' : 'TAP TO FIND',
        'findHeader' : 'Find your device',
        'findContent' : 'Look for your device with this shape on-screen.',
        'foundHeader' : 'Found your device?',
        'foundContent' : 'Were you able to find & experience this device?',
        'yes' : 'YES',
        'no' : 'NO',
        "feedBackHeader1" : 'What do you think?',
        'feedBackContent1' : 'Was this the device of your dreams?',
        'loveIt' : 'LOVE IT',
        'exploreMore' : 'EXPLORE MORE',
        'rr' : 'RATINGS & REVIEWS',
        'feedBackHeader2' : 'Ready to buy?',
        'feedBackContent2' : 'Tap "BUY NOW" and a store associate will be with you shortly?',
        'buyNow' : 'BUY NOW',
        'feedBackHeader3' : 'Contact sales rep ',
        'feedBackContent3' : 'Look for a Retail Professional to help you purchase this today.',
        'backToHome' : 'Back to home',
        'backToStart' : 'BACK',
        'addToWallet' : 'ADD TO WALLET',
        'storeLocDetails' : 'Store Location Details',
        'submit' : 'Submit',
        'latitude' : 'Lattitude',
        'longitude' : 'Longitude',
        'greenLight' : 'Look for the green light to find the device with this shape on-screen.',
        'personalisedDemo' : 'The enjoy a more personalized demo experience of the',
        'couldNotFound' : "Couldn't find it",
        'seeReviews' : 'See reviews',
        'addReview' : 'Add a review',
        'readMore' : 'Read more',
        'notFoundOnDemo' : 'This device is currently not on display for demo.',
        'likeToExploreSimilar' : 'Would you like to explore similar devices?',
        'tapToExplore' : 'EXPLORE MORE',
        'unavailable' : 'Unavailable!',
        'available' : "It's available!",
        'availHeader' : 'Your selected device is now available.',
        'availSubHeader' : "Go ahead , you can now use and experience the product. We'll guide you.",
        'guideMe' : 'GUIDE ME',
        'busy' : "It's busy!",
        'busyHeader' : "Looks like someone's on that device right now.",
        'busySubHeader' : "Explore your other devices while you wait.",
        'atStore' : 'At the store?',
        'atStoreHeader' : 'We could not find you.',
        'atStoreSubHeader' : 'We need you to be in the store with bluetooth enabled on your phone for us to guide you',
        'timeToExplore' : 'Time to explore',
        'tapToActInStoreDemo' : 'Tap to activate your in-store demo.',
        'ctl' : 'Computers & Tablets / Laptops',
        'model' : 'MODEL',
        'sku' : 'SKU',
        'tryAgain' : 'TRY AGAIN',
        'questions' : 'Questions',
        'answers' : 'Answers',
        'onDisplay' : 'on display',
        'changeStore' : 'Change Store',
        'priceMatch' : 'PRICE MATCH',
        'guarantee' : 'GUARANTEE',
        'protectProduct' : 'Protect your product',
        'learnAboutAccidenatalPLans' : 'Learn about Accidental Damage Plans',
        'noPlan' : 'No Plan',
        'selected' : 'Selected',
        'addToCart' : 'Add to Cart',
        'buildBundle' : 'Build a Bundle',
        'savedForLater' : 'SAVED FOR LATER',
        'addForRegistry' : 'ADD FOR REGISTRY',
        'freeShipping' : 'FREE Shipping:',
        'wantItToday' : 'Want it today? Pick it up at Mission Valley or choose',
        'sameDayDelivery' : 'Same-Day Delivery in checkout to 92101',
        'specialOffer' : 'Special Offers',
        'showmore' : 'Showmore',
        'coolDesigns' : 'Cool Designs',
        'betterPerformance' : 'Better Performance',
        'peaceOfMind' : 'Peace of Mind',
        'bestWindowsYet' : 'The best Windows yet',
        'security' : 'Security',
        'microsoftEdge' : 'Microsoft Edge',
        'office' : 'Office',
        'officeContent' : 'The multitasking features of Windows 10 pair perfectly with Office.5 Arrange your screen however you want, easily manage multiple Office apps and docs on one screen, and effortlessly snap up to four of them to optimize your work space. You can also slide the shared edge of snapped apps to wherever you want it, easily resizing both apps in a single motion.',
        'microsoftEdgeContent' : 'Microsoft Edge is designed for Windows 10 and offers faster, safer ways to get more done, across your PC and your phone. And with Microsoft Edge now available on iOS and Android, you get a mobile web experience that’s personal, productive, and responsive. Save groups of tabs, write directly on webpages and share your mark-ups, and read online articles and ebooks free of distractions.',
        'securityContent' : 'Windows provides comprehensive security, including Windows Defender, Firewall, and SmartScreen Filter, plus a dashboard that shows you device health and security.  Always-enabled free updates2 help keep you current on security and features for the supported lifetime of your device.',
        'bestWIndowsYetContent' : 'One of the greatest things about Windows 10 is that it keeps getting better all the time. New features. Updated security. So the best Windows ever always gives you the best experience possible. Even better, staying up-to-date is easy.',
        'peaceOfMindContent' : 'Windows provides the most comprehensive security with Windows Defender, Firewall, and SmartScreen.',
        'betterPerformanceContent' : 'Windows devices give you better performance, with the fast processors, advanced SSD storage, beautiful displays, and the best gaming graphics available.',
        'coolDesignsContent' : 'Windows powers the broadest range of devices with cool designs – like 2-in-1s, All-in-Ones, and ultraslim PCs – from Microsoft and our partners.',
        'cardMemberOffers' : 'Cardmember Offers',
        'finance12' : '12-Month Financing',
        'finance6' : '6-Month Financing',
        'rewards' : 'Get 5% Back in rewards',
        'winLogoData' : 'Windows 10 Pro includes all the features of Windows 10 to support professionals, including non-Microsoft Store apps, domain join, remote desktop and BitLocker.',
        'ofcLogoData' : 'Office 365 is a cloud-based subscription service that brings together the best tools for the way people work today. By combining best-in-className apps like Excel and Outlook with powerful cloud services like OneDrive and Microsoft Teams, Office 365 lets anyone create and share anywhere on any device.',
        'postsHeader' : 'Posts is there',
        'oneStepAway' : "You're one step away!",
        'saveForInStoreExp' : 'Save this to your device for your new in-store experience.',
        'whatDidThink' : 'What did you think of ',
        'saveSessionErr': 'Unable to save session.',
        'browserSettingErr': 'Please switch on your browser location setting.',
        'storeName': 'PopcornApps',
        'passGenerateErr': 'Unable to generate the Wallet Pass.',
        'emptyLat': 'Please Enter Lattitude.',
        'emptyLng': 'Please Enter Longitude.',
        'unableAlert' : 'Unable to send Notification.',
        'locatServFail' : 'The Geolocation service failed.',
        'navNotFound' : 'navigator not found.',
        'browserNotSupportGeo' : "Your browser doesn't support geolocation.",
        'passNotCreated' : 'pass not created',
        'useAnotherBrowser' : 'Please open this link in another browser.',
        'unableToSave' : 'Unable to save',
        'unableContentIos' : 'Tap the lower right icon and choose to open in browser to save your selection on your phone',
        'unableContentAndroid' : 'Tap the top right icon and choose to open in chrome to save your selection on your phone',
        'gotIt' : 'GOT IT',
        'weHaveSol' : 'We have an solution',
        'locationAlertHeader' : 'Could not find you!',
        'enableLocation' : 'Enable your location',
        'locationAlertContent' : 'We need your location for us to enable a pass that can be saved to your phone, making your device experience easier.',
        'convertable' : '2-in-1 Convertible ',
        'usd' : 'USD',
        'expOnDemo' : 'you can experience these devices that are available on demo',
        'yourDevicesHeader' : 'Your devices',
        'alreadyExpDevice' : 'You have already experienced these devices.',
        'someOneUsingDevice' : "Someone's using this device right now.",
        'otherDevices' : 'Other devices',
        'currentlyNotOnDisplayForDemo' : 'The device is currently not on display for demo.',
        'similarDevices' : 'Similar devices',
        'similarDevicesAvailToDemo' : 'We have devices similar to your selection available for demo.',
        'requiredValidations' : 'Invalid Make / Model / StoreId',
    },
    'en-GB' : {
        'youMadeIt': 'You made it!',
        'welcomeHeader' : 'Welcome to Contoso Redmond',
        'welcomeMsg' : 'Walk towards the Microsoft area and tap below when you arrive.',
        'iAmHere' : "I'M HERE!",
        'cancel' : 'CANCEL',
        'landingPageHeader' : 'Find the perfect PC.',
        'chooseSubHeader' : 'choose any option below to explore Windows 10 devices.',
        'panelHeader1' : 'Help Me Choose',
        'panelSubHeader1' : 'Find your perfect device in few easy steps.',
        'panelHeader2' : 'Windows & Office',
        'panelSubHeader2' : 'Explore based on the software and features you use most.',
        'panelSubHeader3' : 'Find devices with all the hardware features you need.',
        'panelHeader3' : 'Hardware',
        'panelHeader4' : 'Windows Premium Collection',
        'panelSubHeader4' : 'View all reommended devices.',
        'recommended' : 'Recommended Devices',
        'learnMore' : 'Learn more',
        'successMsgCaption1' : 'Tap to find your device and look for the ',
        'successMsgCaption2' : 'light',
        'blueLight' : 'blue',
        'tapFind' : 'TAP TO FIND',
        'findHeader' : 'Find your device',
        'findContent' : 'Look for your device with this shape on-screen.',
        'foundHeader' : 'Found your device?',
        'foundContent' : 'Were you able to find & experience this device?',
        'yes' : 'YES',
        'no' : 'NO',
        "feedBackHeader1" : 'What do you think?',
        'feedBackContent1' : 'Was this the device of your dreams?',
        'loveIt' : 'LOVE IT',
        'exploreMore' : 'EXPLORE MORE',
        'rr' : 'RATINGS & REVIEWS',
        'feedBackHeader2' : 'Ready to buy?',
        'feedBackContent2' : 'Tap "BUY NOW" and a store associate will be with you shortly?',
        'buyNow' : 'BUY NOW',
        'feedBackHeader3' : 'Contact sales rep ',
        'feedBackContent3' : 'Look for a Retail Professional to help you purchase this today.',
        'backToHome' : 'Back to home',
        'backToStart' : 'BACK',
        'addToWallet' : 'ADD TO WALLET',
        'storeLocDetails' : 'Store Location Details',
        'submit' : 'Submit',
        'latitude' : 'Lattitude',
        'longitude' : 'Longitude',
        'greenLight' : 'Look for the green light to find the device with this shape on-screen.',
        'personalisedDemo' : 'The enjoy a more personalized demo experience of the',
        'couldNotFound' : "Couldn't find it",
        'seeReviews' : 'See reviews',
        'addReview' : 'Add a review',
        'readMore' : 'Read more',
        'notFoundOnDemo' : 'This device is currently not on display for demo.',
        'likeToExploreSimilar' : 'Would you like to explore similar devices?',
        'tapToExplore' : 'EXPLORE MORE',
        'unavailable' : 'Unavailable!',
        'available' : "It's available!",
        'availHeader' : 'Your selected device is now available.',
        'availSubHeader' : "Go ahead , you can now use and experience the product. We'll guide you.",
        'guideMe' : 'GUIDE ME',
        'busy' : "It's busy!",
        'busyHeader' : "Looks like someone's on that device right now.",
        'busySubHeader' : "Explore your other devices while you wait.",
        'atStore' : 'At the store?',
        'atStoreHeader' : 'We could not find you.',
        'atStoreSubHeader' : 'We need you to be in the store with bluetooth enabled on your phone for us to guide you',
        'timeToExplore' : 'Time to explore',
        'tapToActInStoreDemo' : 'Tap to activate your in-store demo.',
        'ctl' : 'Computers & Tablets / Laptops',
        'model' : 'MODEL',
        'sku' : 'SKU',
        'tryAgain' : 'TRY AGAIN',
        'questions' : 'Questions',
        'answers' : 'Answers',
        'onDisplay' : 'on display',
        'changeStore' : 'Change Store',
        'priceMatch' : 'PRICE MATCH',
        'guarantee' : 'GUARANTEE',
        'protectProduct' : 'Protect your product',
        'learnAboutAccidenatalPLans' : 'Learn about Accidental Damage Plans',
        'noPlan' : 'No Plan',
        'selected' : 'Selected',
        'addToCart' : 'Add to Cart',
        'buildBundle' : 'Build a Bundle',
        'savedForLater' : 'SAVED FOR LATER',
        'addForRegistry' : 'ADD FOR REGISTRY',
        'freeShipping' : 'FREE Shipping:',
        'wantItToday' : 'Want it today? Pick it up at Mission Valley or choose',
        'sameDayDelivery' : 'Same-Day Delivery in checkout to 92101',
        'specialOffer' : 'Special Offers',
        'showmore' : 'Showmore',
        'coolDesigns' : 'Cool Designs',
        'betterPerformance' : 'Better Performance',
        'peaceOfMind' : 'Peace of Mind',
        'bestWindowsYet' : 'The best Windows yet',
        'security' : 'Security',
        'microsoftEdge' : 'Microsoft Edge',
        'office' : 'Office',
        'officeContent' : 'The multitasking features of Windows 10 pair perfectly with Office.5 Arrange your screen however you want, easily manage multiple Office apps and docs on one screen, and effortlessly snap up to four of them to optimize your work space. You can also slide the shared edge of snapped apps to wherever you want it, easily resizing both apps in a single motion.',
        'microsoftEdgeContent' : 'Microsoft Edge is designed for Windows 10 and offers faster, safer ways to get more done, across your PC and your phone. And with Microsoft Edge now available on iOS and Android, you get a mobile web experience that’s personal, productive, and responsive. Save groups of tabs, write directly on webpages and share your mark-ups, and read online articles and ebooks free of distractions.',
        'securityContent' : 'Windows provides comprehensive security, including Windows Defender, Firewall, and SmartScreen Filter, plus a dashboard that shows you device health and security.  Always-enabled free updates2 help keep you current on security and features for the supported lifetime of your device.',
        'bestWIndowsYetContent' : 'One of the greatest things about Windows 10 is that it keeps getting better all the time. New features. Updated security. So the best Windows ever always gives you the best experience possible. Even better, staying up-to-date is easy.',
        'peaceOfMindContent' : 'Windows provides the most comprehensive security with Windows Defender, Firewall, and SmartScreen.',
        'betterPerformanceContent' : 'Windows devices give you better performance, with the fast processors, advanced SSD storage, beautiful displays, and the best gaming graphics available.',
        'coolDesignsContent' : 'Windows powers the broadest range of devices with cool designs – like 2-in-1s, All-in-Ones, and ultraslim PCs – from Microsoft and our partners.',
        'cardMemberOffers' : 'Cardmember Offers',
        'finance12' : '12-Month Financing',
        'finance6' : '6-Month Financing',
        'rewards' : 'Get 5% Back in rewards',
        'winLogoData' : 'Windows 10 Pro includes all the features of Windows 10 to support professionals, including non-Microsoft Store apps, domain join, remote desktop and BitLocker.',
        'ofcLogoData' : 'Office 365 is a cloud-based subscription service that brings together the best tools for the way people work today. By combining best-in-className apps like Excel and Outlook with powerful cloud services like OneDrive and Microsoft Teams, Office 365 lets anyone create and share anywhere on any device.',
        'postsHeader' : 'Posts is there',
        'oneStepAway' : "You're one step away!",
        'saveForInStoreExp' : 'Save this to your device for your new in-store experience.',
        'whatDidThink' : 'What did you think of ',
        'saveSessionErr': 'Unable to save session.',
        'browserSettingErr': 'Please switch on your browser location setting.',
        'storeName': 'PopcornApps',
        'passGenerateErr': 'Unable to generate the Wallet Pass.',
        'emptyLat': 'Please Enter Lattitude.',
        'emptyLng': 'Please Enter Longitude.',
        'unableAlert' : 'Unable to send Notification.',
        'locatServFail' : 'The Geolocation service failed.',
        'navNotFound' : 'navigator not found.',
        'browserNotSupportGeo' : "Your browser doesn't support geolocation.",
        'passNotCreated' : 'pass not created',
        'useAnotherBrowser' : 'Please open this link in another browser.',
        'unableToSave' : 'Unable to save',
        'unableContentIos' : 'Tap the lower right icon and choose to open in browser to save your selection on your phone',
        'unableContentAndroid' : 'Tap the top right icon and choose to open in chrome to save your selection on your phone',
        'gotIt' : 'GOT IT',
        'weHaveSol' : 'We have an solution',
        'locationAlertHeader' : 'Could not find you!',
        'enableLocation' : 'Enable your location',
        'locationAlertContent' : 'We need your location for us to enable a pass that can be saved to your phone, making your device experience easier.',
        'convertable' : '2-in-1 Convertible ',
        'usd' : 'USD',
        'expOnDemo' : 'you can experience these devices that are available on demo',
        'yourDevicesHeader' : 'Your devices',
        'alreadyExpDevice' : 'You have already experienced these devices.',
        'someOneUsingDevice' : "Someone's using this device right now.",
        'otherDevices' : 'Other devices',
        'currentlyNotOnDisplayForDemo' : 'The device is currently not on display for demo.',
        'similarDevices' : 'Similar devices',
        'similarDevicesAvailToDemo' : 'We have devices similar to your selection available for demo.',
        'requiredValidations' : 'Invalid Make / Model / StoreId',
    },
    'fr' : {
        'youMadeIt': "Tu l'as fait!",
        'welcomeHeader' : 'Bienvenue chez Contoso Redmond',
        'welcomeMsg' : 'Dirigez-vous vers la zone Microsoft et appuyez dessus lorsque vous arrivez.',
        'iAmHere' : "JE SUIS ICI!",
        'cancel' : 'ANNULER',
        'landingPageHeader' : 'Find the perfect PC.',
        'chooseSubHeader' : 'choose any option below to explore Windows 10 devices.',
        'panelHeader1' : 'Help Me Choose',
        'panelSubHeader1' : 'Find your perfect device in few easy steps.',
        'panelHeader2' : 'Windows & Office',
        'panelSubHeader2' : 'Explore based on the software and features you use most.',
        'panelSubHeader3' : 'Find devices with all the hardware features you need.',
        'panelHeader3' : 'Hardware',
        'panelHeader4' : 'Windows Premium Collection',
        'panelSubHeader4' : 'View all reommended devices.',
        'recommended' : 'Recommended Devices',
        'learnMore' : 'Learn more',
        'successMsgCaption1' : 'Tap to find your device and look for the ',
        'successMsgCaption2' : 'light',
        'blueLight' : 'blue',
        'tapFind' : 'TAP À TROUVER',
        'findHeader' : 'Find your device',
        'findContent' : "Recherchez votre appareil avec cette forme à l'écran.",
        'foundHeader' : 'Vous avez trouvé votre appareil?',
        'foundContent' : 'Avez-vous pu trouver et expérimenter cet appareil?',
        'yes' : 'YES',
        'no' : 'NO',
        "feedBackHeader1" : "Qu'est-ce que tu penses?",
        'feedBackContent1' : "Était-ce l'appareil de vos rêves?",
        'loveIt' : 'AIMER',
        'exploreMore' : 'EXPLORE PLUS',
        'rr' : 'NOTATIONS ET AVIS',
        'feedBackHeader2' : 'Ready to buy?',
        'feedBackContent2' : 'Tap "BUY NOW" and a store associate will be with you shortly?',
        'buyNow' : 'BUY NOW',
        'feedBackHeader3' : 'Contacter le représentant des ventes ',
        'feedBackContent3' : "Recherchez un professionnel de la vente au détail pour vous aider à acheter ce produit aujourd'hui.",
        'backToHome' : 'De retour à la maison',
        'backToStart' : 'BACK',
        'addToWallet' : 'AJOUTER AU PORTEFEUILLE',
        'storeLocDetails' : 'Store Location Details',
        'submit' : 'Submit',
        'latitude' : 'Lattitude',
        'longitude' : 'Longitude',
        'greenLight' : 'Look for the green light to find the device with this shape on-screen.',
        'personalisedDemo' : 'The enjoy a more personalized demo experience of the',
        'couldNotFound' : "Couldn't find it",
        'seeReviews' : 'See reviews',
        'addReview' : 'Add a review',
        'readMore' : 'Read more',
        'notFoundOnDemo' : "Cet appareil n'est actuellement pas affiché pour la démonstration.",
        'likeToExploreSimilar' : 'Voulez-vous explorer des appareils similaires?',
        'tapToExplore' : 'EXPLORE PLUS',
        'unavailable' : 'Unavailable!',
        'available' : "C'est disponible!",
        'availHeader' : 'Votre appareil sélectionné est maintenant disponible.',
        'availSubHeader' : "Allez-y, vous pouvez maintenant utiliser et expérimenter le produit. Nous vous guiderons.",
        'guideMe' : 'GUIDE MOI',
        'busy' : "It's busy!",
        'busyHeader' : "On dirait que quelqu'un est sur cet appareil maintenant.",
        'busySubHeader' : "Explore your other devices while you wait.",
        'atStore' : 'Au magasin?',
        'atStoreHeader' : "Nous n'avons pas pu vous trouver.",
        'atStoreSubHeader' : 'Nous avons besoin que vous soyez dans le magasin avec Bluetooth activé sur votre téléphone pour que nous puissions vous guider',
        'timeToExplore' : 'Time to explore',
        'tapToActInStoreDemo' : 'Tap to activate your in-store demo.',
        'ctl' : 'Computers & Tablets / Laptops',
        'model' : 'MODEL',
        'sku' : 'SKU',
        'tryAgain' : 'TRY AGAIN',
        'questions' : 'Questions',
        'answers' : 'Answers',
        'onDisplay' : 'on display',
        'changeStore' : 'Change Store',
        'priceMatch' : 'PRICE MATCH',
        'guarantee' : 'GUARANTEE',
        'protectProduct' : 'Protect your product',
        'learnAboutAccidenatalPLans' : 'Learn about Accidental Damage Plans',
        'noPlan' : 'No Plan',
        'selected' : 'Selected',
        'addToCart' : 'Add to Cart',
        'buildBundle' : 'Build a Bundle',
        'savedForLater' : 'SAVED FOR LATER',
        'addForRegistry' : 'ADD FOR REGISTRY',
        'freeShipping' : 'FREE Shipping:',
        'wantItToday' : 'Want it today? Pick it up at Mission Valley or choose',
        'sameDayDelivery' : 'Same-Day Delivery in checkout to 92101',
        'specialOffer' : 'Special Offers',
        'showmore' : 'Showmore',
        'coolDesigns' : 'Cool Designs',
        'betterPerformance' : 'Better Performance',
        'peaceOfMind' : 'Peace of Mind',
        'bestWindowsYet' : 'The best Windows yet',
        'security' : 'Security',
        'microsoftEdge' : 'Microsoft Edge',
        'office' : 'Office',
        'officeContent' : 'The multitasking features of Windows 10 pair perfectly with Office.5 Arrange your screen however you want, easily manage multiple Office apps and docs on one screen, and effortlessly snap up to four of them to optimize your work space. You can also slide the shared edge of snapped apps to wherever you want it, easily resizing both apps in a single motion.',
        'microsoftEdgeContent' : 'Microsoft Edge is designed for Windows 10 and offers faster, safer ways to get more done, across your PC and your phone. And with Microsoft Edge now available on iOS and Android, you get a mobile web experience that’s personal, productive, and responsive. Save groups of tabs, write directly on webpages and share your mark-ups, and read online articles and ebooks free of distractions.',
        'securityContent' : 'Windows provides comprehensive security, including Windows Defender, Firewall, and SmartScreen Filter, plus a dashboard that shows you device health and security.  Always-enabled free updates2 help keep you current on security and features for the supported lifetime of your device.',
        'bestWIndowsYetContent' : 'One of the greatest things about Windows 10 is that it keeps getting better all the time. New features. Updated security. So the best Windows ever always gives you the best experience possible. Even better, staying up-to-date is easy.',
        'peaceOfMindContent' : 'Windows provides the most comprehensive security with Windows Defender, Firewall, and SmartScreen.',
        'betterPerformanceContent' : 'Windows devices give you better performance, with the fast processors, advanced SSD storage, beautiful displays, and the best gaming graphics available.',
        'coolDesignsContent' : 'Windows powers the broadest range of devices with cool designs – like 2-in-1s, All-in-Ones, and ultraslim PCs – from Microsoft and our partners.',
        'cardMemberOffers' : 'Cardmember Offers',
        'finance12' : '12-Month Financing',
        'finance6' : '6-Month Financing',
        'rewards' : 'Get 5% Back in rewards',
        'winLogoData' : 'Windows 10 Pro includes all the features of Windows 10 to support professionals, including non-Microsoft Store apps, domain join, remote desktop and BitLocker.',
        'ofcLogoData' : 'Office 365 is a cloud-based subscription service that brings together the best tools for the way people work today. By combining best-in-className apps like Excel and Outlook with powerful cloud services like OneDrive and Microsoft Teams, Office 365 lets anyone create and share anywhere on any device.',
        'postsHeader' : 'Posts is there',
        'oneStepAway' : "You're one step away!",
        'saveForInStoreExp' : 'Enregistrez-le sur votre appareil pour votre nouvelle expérience en magasin.',
        'whatDidThink' : 'What did you think of ',
        'saveSessionErr': 'Unable to save session.',
        'browserSettingErr': "Veuillez activer le paramètre d'emplacement de votre navigateur.",
        'storeName': 'PopcornApps',
        'passGenerateErr': 'Unable to generate the Wallet Pass.',
        'emptyLat': 'Please Enter Lattitude.',
        'emptyLng': 'Please Enter Longitude.',
        'unableAlert' : 'Unable to send Notification.',
        'locatServFail' : 'Le service de géolocalisation a échoué.',
        'navNotFound' : 'navigator not found.',
        'browserNotSupportGeo' : "Your browser doesn't support geolocation.",
        'passNotCreated' : 'pass not created',
        'useAnotherBrowser' : 'Veuillez ouvrir ce lien dans un autre navigateur.',
        'unableToSave' : 'Impossible de sauvegarder',
        'unableContentIos' : "Appuyez sur l'icône en bas à droite et choisissez d'ouvrir dans le navigateur pour enregistrer votre sélection sur votre téléphone.",
        'unableContentAndroid' : "Appuyez sur l'icône en haut à droite et choisissez d'ouvrir en chrome pour enregistrer votre sélection sur votre téléphone.",
        'gotIt' : 'GOT IT',
        'weHaveSol' : 'Nous avons une solution',
        'locationAlertHeader' : 'Impossible de te trouver!',
        'enableLocation' : 'Activer votre position',
        'locationAlertContent' : "Nous avons besoin de votre emplacement pour activer un pass qui peut être enregistré sur votre téléphone, facilitant ainsi l'expérience de votre appareil.",
        'convertable' : '2-in-1 Convertible ',
        'usd' : 'USD',
        'expOnDemo' : 'you can experience these devices that are available on demo',
        'yourDevicesHeader' : 'Vos appareils',
        'alreadyExpDevice' : 'Vous avez déjà expérimenté ces appareils.',
        'someOneUsingDevice' : "Quelqu'un utilise cet appareil maintenant.",
        'otherDevices' : 'Autres appareils',
        'currentlyNotOnDisplayForDemo' : "L'appareil n'est actuellement pas affiché pour la démonstration.",
        'similarDevices' : 'Appareils similaires',
        'similarDevicesAvailToDemo' : 'Nous avons des appareils similaires à votre sélection disponibles pour la démonstration.',
        'requiredValidations' : 'Invalid Make / Model / StoreId',
    },
    'fr-Fr' : {
        'youMadeIt': "Tu l'as fait!",
        'welcomeHeader' : 'Bienvenue chez Contoso Redmond',
        'welcomeMsg' : 'Dirigez-vous vers la zone Microsoft et appuyez dessus lorsque vous arrivez.',
        'iAmHere' : "JE SUIS ICI!",
        'cancel' : 'ANNULER',
        'landingPageHeader' : 'Find the perfect PC.',
        'chooseSubHeader' : 'choose any option below to explore Windows 10 devices.',
        'panelHeader1' : 'Help Me Choose',
        'panelSubHeader1' : 'Find your perfect device in few easy steps.',
        'panelHeader2' : 'Windows & Office',
        'panelSubHeader2' : 'Explore based on the software and features you use most.',
        'panelSubHeader3' : 'Find devices with all the hardware features you need.',
        'panelHeader3' : 'Hardware',
        'panelHeader4' : 'Windows Premium Collection',
        'panelSubHeader4' : 'View all reommended devices.',
        'recommended' : 'Recommended Devices',
        'learnMore' : 'Learn more',
        'successMsgCaption1' : 'Tap to find your device and look for the ',
        'successMsgCaption2' : 'light',
        'blueLight' : 'blue',
        'tapFind' : 'TAP À TROUVER',
        'findHeader' : 'Find your device',
        'findContent' : "Recherchez votre appareil avec cette forme à l'écran.",
        'foundHeader' : 'Vous avez trouvé votre appareil?',
        'foundContent' : 'Avez-vous pu trouver et expérimenter cet appareil?',
        'yes' : 'YES',
        'no' : 'NO',
        "feedBackHeader1" : "Qu'est-ce que tu penses?",
        'feedBackContent1' : "Était-ce l'appareil de vos rêves?",
        'loveIt' : 'AIMER',
        'exploreMore' : 'EXPLORE PLUS',
        'rr' : 'NOTATIONS ET AVIS',
        'feedBackHeader2' : 'Ready to buy?',
        'feedBackContent2' : 'Tap "BUY NOW" and a store associate will be with you shortly?',
        'buyNow' : 'BUY NOW',
        'feedBackHeader3' : 'Contacter le représentant des ventes ',
        'feedBackContent3' : "Recherchez un professionnel de la vente au détail pour vous aider à acheter ce produit aujourd'hui.",
        'backToHome' : 'De retour à la maison',
        'backToStart' : 'BACK',
        'addToWallet' : 'AJOUTER AU PORTEFEUILLE',
        'storeLocDetails' : 'Store Location Details',
        'submit' : 'Submit',
        'latitude' : 'Lattitude',
        'longitude' : 'Longitude',
        'greenLight' : 'Look for the green light to find the device with this shape on-screen.',
        'personalisedDemo' : 'The enjoy a more personalized demo experience of the',
        'couldNotFound' : "Couldn't find it",
        'seeReviews' : 'See reviews',
        'addReview' : 'Add a review',
        'readMore' : 'Read more',
        'notFoundOnDemo' : "Cet appareil n'est actuellement pas affiché pour la démonstration.",
        'likeToExploreSimilar' : 'Voulez-vous explorer des appareils similaires?',
        'tapToExplore' : 'EXPLORE PLUS',
        'unavailable' : 'Unavailable!',
        'available' : "C'est disponible!",
        'availHeader' : 'Votre appareil sélectionné est maintenant disponible.',
        'availSubHeader' : "Allez-y, vous pouvez maintenant utiliser et expérimenter le produit. Nous vous guiderons.",
        'guideMe' : 'GUIDE MOI',
        'busy' : "It's busy!",
        'busyHeader' : "On dirait que quelqu'un est sur cet appareil maintenant.",
        'busySubHeader' : "Explore your other devices while you wait.",
        'atStore' : 'Au magasin?',
        'atStoreHeader' : "Nous n'avons pas pu vous trouver.",
        'atStoreSubHeader' : 'Nous avons besoin que vous soyez dans le magasin avec Bluetooth activé sur votre téléphone pour que nous puissions vous guider',
        'timeToExplore' : 'Time to explore',
        'tapToActInStoreDemo' : 'Tap to activate your in-store demo.',
        'ctl' : 'Computers & Tablets / Laptops',
        'model' : 'MODEL',
        'sku' : 'SKU',
        'tryAgain' : 'TRY AGAIN',
        'questions' : 'Questions',
        'answers' : 'Answers',
        'onDisplay' : 'on display',
        'changeStore' : 'Change Store',
        'priceMatch' : 'PRICE MATCH',
        'guarantee' : 'GUARANTEE',
        'protectProduct' : 'Protect your product',
        'learnAboutAccidenatalPLans' : 'Learn about Accidental Damage Plans',
        'noPlan' : 'No Plan',
        'selected' : 'Selected',
        'addToCart' : 'Add to Cart',
        'buildBundle' : 'Build a Bundle',
        'savedForLater' : 'SAVED FOR LATER',
        'addForRegistry' : 'ADD FOR REGISTRY',
        'freeShipping' : 'FREE Shipping:',
        'wantItToday' : 'Want it today? Pick it up at Mission Valley or choose',
        'sameDayDelivery' : 'Same-Day Delivery in checkout to 92101',
        'specialOffer' : 'Special Offers',
        'showmore' : 'Showmore',
        'coolDesigns' : 'Cool Designs',
        'betterPerformance' : 'Better Performance',
        'peaceOfMind' : 'Peace of Mind',
        'bestWindowsYet' : 'The best Windows yet',
        'security' : 'Security',
        'microsoftEdge' : 'Microsoft Edge',
        'office' : 'Office',
        'officeContent' : 'The multitasking features of Windows 10 pair perfectly with Office.5 Arrange your screen however you want, easily manage multiple Office apps and docs on one screen, and effortlessly snap up to four of them to optimize your work space. You can also slide the shared edge of snapped apps to wherever you want it, easily resizing both apps in a single motion.',
        'microsoftEdgeContent' : 'Microsoft Edge is designed for Windows 10 and offers faster, safer ways to get more done, across your PC and your phone. And with Microsoft Edge now available on iOS and Android, you get a mobile web experience that’s personal, productive, and responsive. Save groups of tabs, write directly on webpages and share your mark-ups, and read online articles and ebooks free of distractions.',
        'securityContent' : 'Windows provides comprehensive security, including Windows Defender, Firewall, and SmartScreen Filter, plus a dashboard that shows you device health and security.  Always-enabled free updates2 help keep you current on security and features for the supported lifetime of your device.',
        'bestWIndowsYetContent' : 'One of the greatest things about Windows 10 is that it keeps getting better all the time. New features. Updated security. So the best Windows ever always gives you the best experience possible. Even better, staying up-to-date is easy.',
        'peaceOfMindContent' : 'Windows provides the most comprehensive security with Windows Defender, Firewall, and SmartScreen.',
        'betterPerformanceContent' : 'Windows devices give you better performance, with the fast processors, advanced SSD storage, beautiful displays, and the best gaming graphics available.',
        'coolDesignsContent' : 'Windows powers the broadest range of devices with cool designs – like 2-in-1s, All-in-Ones, and ultraslim PCs – from Microsoft and our partners.',
        'cardMemberOffers' : 'Cardmember Offers',
        'finance12' : '12-Month Financing',
        'finance6' : '6-Month Financing',
        'rewards' : 'Get 5% Back in rewards',
        'winLogoData' : 'Windows 10 Pro includes all the features of Windows 10 to support professionals, including non-Microsoft Store apps, domain join, remote desktop and BitLocker.',
        'ofcLogoData' : 'Office 365 is a cloud-based subscription service that brings together the best tools for the way people work today. By combining best-in-className apps like Excel and Outlook with powerful cloud services like OneDrive and Microsoft Teams, Office 365 lets anyone create and share anywhere on any device.',
        'postsHeader' : 'Posts is there',
        'oneStepAway' : "You're one step away!",
        'saveForInStoreExp' : 'Enregistrez-le sur votre appareil pour votre nouvelle expérience en magasin.',
        'whatDidThink' : 'What did you think of ',
        'saveSessionErr': 'Unable to save session.',
        'browserSettingErr': "Veuillez activer le paramètre d'emplacement de votre navigateur.",
        'storeName': 'PopcornApps',
        'passGenerateErr': 'Unable to generate the Wallet Pass.',
        'emptyLat': 'Please Enter Lattitude.',
        'emptyLng': 'Please Enter Longitude.',
        'unableAlert' : 'Unable to send Notification.',
        'locatServFail' : 'Le service de géolocalisation a échoué.',
        'navNotFound' : 'navigator not found.',
        'browserNotSupportGeo' : "Your browser doesn't support geolocation.",
        'passNotCreated' : 'pass not created',
        'useAnotherBrowser' : 'Veuillez ouvrir ce lien dans un autre navigateur.',
        'unableToSave' : 'Impossible de sauvegarder',
        'unableContentIos' : "Appuyez sur l'icône en bas à droite et choisissez d'ouvrir dans le navigateur pour enregistrer votre sélection sur votre téléphone.",
        'unableContentAndroid' : "Appuyez sur l'icône en haut à droite et choisissez d'ouvrir en chrome pour enregistrer votre sélection sur votre téléphone.",
        'gotIt' : 'GOT IT',
        'weHaveSol' : 'Nous avons une solution',
        'locationAlertHeader' : 'Impossible de te trouver!',
        'enableLocation' : 'Activer votre position',
        'locationAlertContent' : "Nous avons besoin de votre emplacement pour activer un pass qui peut être enregistré sur votre téléphone, facilitant ainsi l'expérience de votre appareil.",
        'convertable' : '2-in-1 Convertible ',
        'usd' : 'USD',
        'expOnDemo' : 'you can experience these devices that are available on demo',
        'yourDevicesHeader' : 'Vos appareils',
        'alreadyExpDevice' : 'Vous avez déjà expérimenté ces appareils.',
        'someOneUsingDevice' : "Quelqu'un utilise cet appareil maintenant.",
        'otherDevices' : 'Autres appareils',
        'currentlyNotOnDisplayForDemo' : "L'appareil n'est actuellement pas affiché pour la démonstration.",
        'similarDevices' : 'Appareils similaires',
        'similarDevicesAvailToDemo' : 'Nous avons des appareils similaires à votre sélection disponibles pour la démonstration.',
        'requiredValidations' : 'Invalid Make / Model / StoreId',
    },

};
export default userLanguage;