const userLanguage = {
	'en' : {
    'youMadeIt': 'You made it!',
    'welcomeHeader' : 'Welcome to Contoso Redmond',
    'welcomeMsg' : 'Walk towards the Microsoft area and tap below when you arrive.',
    'iAmHere' : "I'M HERE!",
    'cancel' : 'CANCEL',
    'landingPageHeader' : 'Find the perfect PC.',
    'chooseSubHeader' : 'choose any option below to explore Windows 10 devices.',
    'panelHeader1' : 'Help Me Choose',
    'panelSubHeader1' : 'Find your perfect device in few easy steps.',
    'panelHeader2' : 'Windows & Office',
    'panelSubHeader2' : 'Explore based on the software and features you use most.',
    'panelSubHeader3' : 'Find devices with all the hardware features you need.',
    'panelHeader3' : 'Hardware',
    'panelHeader4' : 'Windows Premium Collection',
    'panelSubHeader4' : 'View all reommended devices.',
    'recommended' : 'Recommended Devices',
    'learnMore' : 'Learn more',
    'successMsgCaption1' : 'Tap to find your device and look for the ',
    'successMsgCaption2' : 'light',
    'blueLight' : 'blue',
    'tapFind' : 'TAP TO FIND',
    'findHeader' : 'Find your device',
    'findContent' : 'Look for your device with this shape on-screen.',
    'foundHeader' : 'Found your device?',
    'foundContent' : 'Were you able to find & experience this device?',
    'yes' : 'YES',
    'no' : 'NO',
    "feedBackHeader1" : 'What do you think?',
    'feedBackContent1' : 'Was this the device of your dreams?',
    'loveIt' : 'LOVE IT',
    'exploreMore' : 'EXPLORE MORE',
    'rr' : 'RATINGS & REVIEWS',
    'feedBackHeader2' : 'Ready to buy?',
    'feedBackContent2' : 'Tap "BUY NOW" and a store associate will be with you shortly?',
    'buyNow' : 'BUY NOW',
    'feedBackHeader3' : 'Contact sales rep ',
    'feedBackContent3' : 'Look for a Retail Professional to help you purchase this today.',
    'backToHome' : 'Back to home',
    'backToStart' : 'BACK TO START',
    'addToWallet' : 'ADD TO WALLET',
    'storeLocDetails' : 'Store Location Details',
    'submit' : 'Submit',
    'latitude' : 'Lattitude',
    'longitude' : 'Longitude',
    'greenLight' : 'Look for the green light to find the device with this shape on-screen.',
    'personalisedDemo' : 'The enjoy a more personalized demo experience of the',
    'couldNotFound' : "Couldn't find it",
    'seeReviews' : 'See reviews',
    'addReview' : 'Add a review',
    'readMore' : 'Read more',
    'notFoundOnDemo' : 'This device is currently not on display for demo.',
    'likeToExploreSimilar' : 'Would you like to explore similar devices?',
    'tapToExplore' : 'TAP TO EXPLORE',
    'unavailable' : 'unavailable!',
    'available' : "It's available!",
    'availHeader' : 'Your selected device is now available.',
    'availSubHeader' : "Go ahead , you can now use and experience the product. We'll guide you.",
    'guideMe' : 'GUIDE ME',
    'busy' : "It's busy!",
    'busyHeader' : "Looks like someone's on that device right now.",
    'busySubHeader' : "Explore your other devices while you wait.",
    'atStore' : 'At the store?',
    'atStoreHeader' : 'We could not find you.',
    'atStoreSubHeader' : 'We need you to be in the store with bluetooth enabled on your phone for us to guide you',
    'timeToExplore' : 'Time to explore',
    'tapToActInStoreDemo' : 'Tap to activate your in-store demo.',
    'ctl' : 'Computers & Tablets / Laptops',
    'model' : 'MODEL',
    'sku' : 'SKU',
    'tryAgain' : 'TRY AGAIN',
    'questions' : 'Questions',
    'answers' : 'Answers',
    'onDisplay' : 'on display',
    'changeStore' : 'Change Store',
    'priceMatch' : 'PRICE MATCH',
    'guarantee' : 'GUARANTEE',
    'protectProduct' : 'Protect your product',
    'learnAboutAccidenatalPLans' : 'Learn about Accidental Damage Plans',
    'noPlan' : 'No Plan',
    'selected' : 'Selected',
    'addToCart' : 'Add to Cart',
    'buildBundle' : 'Build a Bundle',
    'savedForLater' : 'SAVED FOR LATER',
    'addForRegistry' : 'ADD FOR REGISTRY',
    'freeShipping' : 'FREE Shipping:',
    'wantItToday' : 'Want it today? Pick it up at Mission Valley or choose',
    'sameDayDelivery' : 'Same-Day Delivery in checkout to 92101',
    'specialOffer' : 'Special Offers',
    'showmore' : 'Showmore',
    'coolDesigns' : 'Cool Designs',
    'betterPerformance' : 'Better Performance',
    'peaceOfMind' : 'Peace of Mind',
    'bestWindowsYet' : 'The best Windows yet',
    'security' : 'Security',
    'microsoftEdge' : 'Microsoft Edge',
    'office' : 'Office',
    'officeContent' : 'The multitasking features of Windows 10 pair perfectly with Office.5 Arrange your screen however you want, easily manage multiple Office apps and docs on one screen, and effortlessly snap up to four of them to optimize your work space. You can also slide the shared edge of snapped apps to wherever you want it, easily resizing both apps in a single motion.',
    'microsoftEdgeContent' : 'Microsoft Edge is designed for Windows 10 and offers faster, safer ways to get more done, across your PC and your phone. And with Microsoft Edge now available on iOS and Android, you get a mobile web experience that’s personal, productive, and responsive. Save groups of tabs, write directly on webpages and share your mark-ups, and read online articles and ebooks free of distractions.',
    'securityContent' : 'Windows provides comprehensive security, including Windows Defender, Firewall, and SmartScreen Filter, plus a dashboard that shows you device health and security.  Always-enabled free updates2 help keep you current on security and features for the supported lifetime of your device.',
    'bestWIndowsYetContent' : 'One of the greatest things about Windows 10 is that it keeps getting better all the time. New features. Updated security. So the best Windows ever always gives you the best experience possible. Even better, staying up-to-date is easy.',
    'peaceOfMindContent' : 'Windows provides the most comprehensive security with Windows Defender, Firewall, and SmartScreen.',
    'betterPerformanceContent' : 'Windows devices give you better performance, with the fast processors, advanced SSD storage, beautiful displays, and the best gaming graphics available.',
    'coolDesignsContent' : 'Windows powers the broadest range of devices with cool designs – like 2-in-1s, All-in-Ones, and ultraslim PCs – from Microsoft and our partners.',
    'cardMemberOffers' : 'Cardmember Offers',
    'finance12' : '12-Month Financing',
    'finance6' : '6-Month Financing',
    'rewards' : 'Get 5% Back in rewards',
    'winLogoData' : 'Windows 10 Pro includes all the features of Windows 10 to support professionals, including non-Microsoft Store apps, domain join, remote desktop and BitLocker.',
    'ofcLogoData' : 'Office 365 is a cloud-based subscription service that brings together the best tools for the way people work today. By combining best-in-className apps like Excel and Outlook with powerful cloud services like OneDrive and Microsoft Teams, Office 365 lets anyone create and share anywhere on any device.',
    'postsHeader' : 'Posts is there',
    'oneStepAway' : "You're one step away!",
    'saveForInStoreExp' : 'Save this to your device for your new in-store experience.',
    'whatDidThink' : 'What did you think of ',
    'unableToSave' : 'Unable to save',
    'unableContent1' : 'Tap the lower right icon and choose to',
    'unableContent2' : 'open in browser to save your',
    'unableContent3' : 'selection on your phone',
    'gotIt' : 'GOT IT',
    'weHaveSol' : 'We have an solution'
	}
};
export default userLanguage;